In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [2]:
data = [
    {"id": 1, "name": "Arduino Kit", "category": "Hardware", "quantity": 5, "status": "Available"},
    {"id": 2, "name": "Figma License", "category": "Software", "quantity": 20, "status": "Available"},
    {"id": 3, "name": "Soldering Iron", "category": "Hardware", "quantity": 0, "status": "Unavailable"}
]

In [3]:
df = pd.DataFrame(data)
df.head()

   id            name  category  quantity       status
0   1     Arduino Kit  Hardware         5    Available
1   2   Figma License  Software        20    Available
2   3  Soldering Iron  Hardware         0  Unavailable

In [ ]:
# Compute total number of items
int(df['quantity'].sum())

25

In [6]:
# Group items by category
df.groupby('category')['quantity'].sum()

category
Hardware     5
Software    20
Name: quantity, dtype: int64

In [7]:
# Low Stock
low_stock= df[df['quantity'] < 5]
low_stock.head()

   id            name  category  quantity       status
2   3  Soldering Iron  Hardware         0  Unavailable